TBM_terms_list = ['Technology Business Management',
            'TBM',
            'TBMA',
            'IT Spending Transparency',
            'Cost Transparency',
            'TBM Framework',
            'Standard Taxonomy',
            'IT Cost Reporting',
            'General Ledger',
            'Business Units',
            'Business Capabilities',
            'Products & Services',
            'IT Towers',
            'sub-towers',
            'Cost Pools',
            'sub-pools',
            'Finance View',
            'IT View',
            'Business View',
            'Mission View']